//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadgeEventSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BadgeEventSet()
        {
            this.PositionSets = new HashSet<PositionSet>();
            this.RuleSets = new HashSet<RuleSet>();
        }
    
        public int ID_BadgeEvent { get; set; }
        public int EventID_Event { get; set; }
        public int BadgeID_Badge { get; set; }
        public string Name { get; set; }
        public bool DefaultPrint { get; set; }
        public string BackgroundImage { get; set; }
    
        public virtual BadgeSet BadgeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionSet> PositionSets { get; set; }
        public virtual EventSet EventSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSet> RuleSets { get; set; }
    }
}
