//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyBadgeModelContext : DbContext
    {
        public EasyBadgeModelContext()
            : base("name=EasyBadgeModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BadgeEventSet> BadgeEventSets { get; set; }
        public virtual DbSet<BadgeSet> BadgeSets { get; set; }
        public virtual DbSet<EventFieldSet> EventFieldSets { get; set; }
        public virtual DbSet<EventFieldUserSet> EventFieldUserSets { get; set; }
        public virtual DbSet<EventSet> EventSets { get; set; }
        public virtual DbSet<FieldSet> FieldSets { get; set; }
        public virtual DbSet<FilterSet> FilterSets { get; set; }
        public virtual DbSet<PositionSet> PositionSets { get; set; }
        public virtual DbSet<PrintBadgeSet> PrintBadgeSets { get; set; }
        public virtual DbSet<RuleSet> RuleSets { get; set; }
        public virtual DbSet<TargetSet> TargetSets { get; set; }
        public virtual DbSet<UserSet> UserSets { get; set; }
    }
}
