//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyModelContext : DbContext
    {
        public EasyModelContext()
            : base("name=EasyModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Event> EventSet { get; set; }
        public virtual DbSet<Field> FieldSet { get; set; }
        public virtual DbSet<EventFieldUser> EventFieldUserSet { get; set; }
        public virtual DbSet<PrintBadge> PrintBadgeSet { get; set; }
        public virtual DbSet<Badge> BadgeSet { get; set; }
        public virtual DbSet<BadgeEvent> BadgeEventSet { get; set; }
        public virtual DbSet<Position> PositionSet { get; set; }
        public virtual DbSet<EventField> EventFieldSet { get; set; }
    }
}
