//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventFieldUserSet
    {
        public int UserID_User { get; set; }
        public int EventFieldFieldID_Field { get; set; }
        public int EventFieldEventID_Event { get; set; }
        public string Value { get; set; }
        public string AdditionnalInformation { get; set; }
    
        public virtual EventFieldSet EventFieldSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
