//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventFieldSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventFieldSet()
        {
            this.EventFieldUserSets = new HashSet<EventFieldUserSet>();
            this.FilterSets = new HashSet<FilterSet>();
        }
    
        public int FieldID_Field { get; set; }
        public int EventID_Event { get; set; }
        public bool Visibility { get; set; }
        public bool Unique { get; set; }
    
        public virtual EventSet EventSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventFieldUserSet> EventFieldUserSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilterSet> FilterSets { get; set; }
        public virtual FieldSet FieldSet { get; set; }
    }
}
