//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilterSet()
        {
            this.RuleSets = new HashSet<RuleSet>();
        }
    
        public int ID_Filter { get; set; }
        public int EventFieldFieldID_Field { get; set; }
        public int EventFieldEventID_Event { get; set; }
        public string LogicalOperator { get; set; }
        public string Value { get; set; }
    
        public virtual EventFieldSet EventFieldSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSet> RuleSets { get; set; }
    }
}
