//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionSet
    {
        public int ID_Position { get; set; }
        public int FieldID_Field { get; set; }
        public int BadgeEventID_BadgeEvent { get; set; }
        public double Position_X { get; set; }
        public double Position_Y { get; set; }
        public string FontFamily { get; set; }
        public double FontSize { get; set; }
        public string FontStyle { get; set; }
        public Nullable<double> AngleRotation { get; set; }
    
        public virtual BadgeEventSet BadgeEventSet { get; set; }
        public virtual FieldSet FieldSet { get; set; }
    }
}
