//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintBadgeSet
    {
        public int ID_PrintBadge { get; set; }
        public System.DateTime PrintDate { get; set; }
        public string PrintBy { get; set; }
        public string Comment { get; set; }
        public int UserID_User { get; set; }
        public int EventID_Event { get; set; }
    
        public virtual EventSet EventSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
