//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBadgeMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int ID_Rule { get; set; }
        public int FilterID_Filter { get; set; }
        public string HexaCode { get; set; }
        public int TargetID_Target { get; set; }
        public int BadgeEventID_BadgeEvent { get; set; }
    
        public virtual Filter Filter { get; set; }
        public virtual Target Target { get; set; }
        public virtual BadgeEvent BadgeEvent { get; set; }
    }
}
